//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoUm.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ferramenta
    {
        [Key, ScaffoldColumn(false)]
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Diametro { get; set; }
        [Display (Name = "Lote")]
        public int LoteId { get; set; }
    
        public virtual Lote Lote { get; set; }
    }
}
